---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Vault role
      when: 1 == 2
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_engines"

    - name: Vault role
      when: 1 == 3
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_secrets"
        engine_name: "coffee"

    - name: Vault role
      when: 1 == 3
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_authmethods"

    - name: Vault role
      when: 1 == 1
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_certificates"
        engine_name: "pki-a"
